name: workflow

on:
  push:
    branches:
      -main
    path-ignore:
    - "README.md"

jobs:
  integration:
    name: Continous Integration
    runs-on: ubuntu-latest
    steps:
      -name: Checkout Code
      uses: actions/chcekout@v3

      -name: Lint Code
      uses: echo "Linting Rep"

      -name: Run unit tests
      run: echo "Running Unit Test"
      
